version: '3'
services:
  nuxt-app:
    container_name: nuxt-app
    restart: always
    build: .
    ports: 
      - "5000:5000"
    links:
      - mongo
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'